---
title: "Universidad Santo Tomás, Facultad de Ingeniería"
subtitle: "Control Estadístico de Calidad: Primera prueba parcial" 
author: "Profesor: Gustavo Ahumada"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  theme: united
  html_notebook: default
---

**Exigencia**: $70\%$. **Puntaje total**: 80 puntos. **Tiempo de duración**: 36 horas  

**Instrucciones**: (1) Las respuestas finales deben ser legibles y escritas con lápiz pasta; (2) debe scanear sus respuestas y generar un archivo en PDF, el cual debe ser enviado únicamente al correo electrónico gahumada2@santotomas.cl; (3) la fecha de entrega es el día 17 de mayo a las 12:00 PM.

## Distribuciones de probabilidad

**1. Distribución Binomial**. Considerar el problema de calcular la probabilidad de obtener 6 o mas caras en 10 lanzamiento de una moneda ponderada (no balanceada), donde la probabilidad de obtener una cara en cualquier intento es de $0.33$.

<!--
-->
<!--
**Solución**: Sea la variable aleatoria $X$ igual al número de intentos que resultan en una cara. Consecuentemente, $X\sim Bin(10, 0.33)$, y la suma de las probabilidades individuales de obtener $6,7,8,9$ y $10$ necesitan ser encontradas. Metemáticamente, esto puede escribirse $P(X \ge 6)= P(X=6)+P(X=7)+...+P(X=10)$, donde

\begin{equation} 
\begin{split}
P(X = 6)&  = \frac{10!}{6!(10-6!)} \times 0.33^{6} \times (1-0.33)^{(10-6)} =0.0547, \\
P(X = 7)&  = \frac{10!}{7!(10-7!)} \times 0.33^{7} \times (1-0.33)^{(10-7)} =0.0154, \\
P(X = 8)&  = \frac{10!}{8!(10-8!)} \times 0.33^{8} \times (1-0.33)^{(10-8)} =0.0028, \\
P(X = 9)&  = \frac{10!}{9!(10-9!)} \times 0.33^{9} \times (1-0.33)^{(10-9)} =0.0003, \\
P(X = 10)&  = \frac{10!}{9!(10-9!)} \times 0.33^{9} \times (1-0.33)^{(10-9)} =0. \\
\nonumber
\end{split} 
\end{equation}

Entonces,
\begin{equation} 
\begin{split}
P(X \ge 6) & = P(X=6)+P(X=7)+P(X=8)+P(X=9)+P(X=10) \\
& = 0.0547+0.0154+0.0028+0.0003+0 \\
& = 0.0732.
\nonumber
\end{split} 
\end{equation}

Existen varias aproximaciones para encontrar dicha probabilidad con R

```{r}
sum(dbinom(6:10, 10, 0.33))             # P(X>=6)

1 - pbinom(5, 10, 0.33)                 # 1 - P(X<=5) 

pbinom(5,10,0.33, lower = FALSE)        # P(X>=6)

1- sum(dbinom(5:0, 10, 0.33)) 
```
-->

**2. Distribución normal**. Mucho de los accesorios para teléfonos celulares hoy en día permiten a los consumidores cambiar del altavoz y el micrófono a una fuente externa. Una empresa manufacturera de teléfonos celulares quiere incluir un altavoz y un micrófono para operar con manos libres. Una nueva empresa ha patentado un componente que permite que la planicidad de resistencia para el micrófono y el altavoz sea más baja que nunca. El teléfono celular de la compañía requiere que la planicidad de resistencia sea menor a $0.7$ ohmios ($\Omega$). Si se sabe que el $50\%$ de los componentes de la nueva compañía tiene una proporción de $0.5$ ohmios o menos, $10\%$  tiene una proporción de $0.628$ ohmios y la distribución de estas proporciones sigue una distribución normal, entonces:

1. Encontrar la media y la desviación estándar para la distribución de la proporción de ohmio de los componentes.

2. Si un componente es seleccionado de manera aleatoria, ¿cual es la probabilidad que su planicidad de resistencia sea menor a $0.7$ ohmios?

3. Si $20$ componentes son seleccionados de manera aleatoria, ¿cual es la probabilidad que al menos 19 compnentes tengan una planicidad de resistencia menor a $0.7$ ohmios?

<!--
**Solución**: Sea $X=$ a la proporción de ohmio de los componentes 

1. Debido a la simetria de la distribución normal, la media es igual a la mediana. Es conocido que $50\%$ de los componentes tienen una proporción 
-->

**3. Distribución hipergeométrica**. Se selecciona al azar un comité de siete personas entre tres sociólogos, tres antropólogos y 2 economistas. Encuentre la distribución de probabilidad para el número de economistas en el comité.


<!--
**Solución**:


-->

## Distribuciones muestrales

**4.** La distribución de alturas de cierta raza de perros terrier tiene una altura media de $72$ centímetros y una desviación estándar de 10 centímetros, mientras que la distribución de alturas de cierta raza de poodles tiene una altura de media $28$ centímetros con una desviación estándar de 5 centímetros. Suponga que las medias muestrales se pueden medir con cualquier grado de precisión, encuentre la probabilidad de que la media muestral para una muestra aleatoria de altura de 64 terriers exceda la media para una muestra aleatioria de alturas de 100 poodles por cuando mucho $44.2$ centímetros.

<!--
**Solución**:
224

-->

**5.** Encontrar la probabilidad de que una muestra aleatoria de 25 observaciones, de una población normal con varianza $\sigma^{2} = 6$, tenga una varianza $s^{2}$

1. mayor que $9.1$.

2. entre $3.463$ y $10.745$.

Suponga que las varianzas muestrales son mediciones continuas.


## Intervalos de confianza

**6.** Una muestra aleatoria de tamaño $n_{1}=25$ que se toma de una población normal con una desviación estándar $\sigma_{1}=5$ tiene una media $\bar x_{1}=80$. Una segunda muestra aleatoria de tamaño $n_{2}=36$, que se toma de una población normal diferente con una desviación estándar $\sigma_{2}=3$ tiene una media $\bar x_{2}=75$. Encontrar un intervalo de confianza de $95\%$ para $\mu_{1}-\mu_{2}$.

<!--
**Solución**:
263

-->

## Prueba de hipótesis

**7.** La estatura promedio de mujeres en el grupo de primer año de cierta universidad es de $162.5$ centímetros con una desviación estándar de $6.9$ centímetros con una desviación ¿Hay alguna razón para creer que hay un cambio de estatura si una muestra aleatoria de 50 mujeres en el grupo actual de primer año tiene una altura promedio de $165.2$ centímetros? utilice un valor $P$ pata su conclusión.


**8.** Una compañía de venta de calefacciones afirma que un quinto de las casas en cierta ciudad se calientan con petróleo. ¿Tenemos razón en duda de esta afirmación si, en una muestra aleatoria de 1000 casas en esta ciudad, se encuentra que $136$ se calientan con petróleo? Utilice un nivel de significancia de $0.01$.

<!--
**Solución**:
335

-->

