---
title: "Solucion Taller 2: Distribuciones muestrales de medias"
author: "Gustavo Ahumada"
output:
  pdf_document: default
  html_document:
    df_print: paged
  theme: united
  html_notebook: default
---
# Ejercicios

1. Si se extraen todas las muestras de posible tamaño $16$ de una población normal con media igual a 50 y desviación estándar igual a 5, ¿cuál es la probabilidad de que una media muestral $\bar X$ caiga en el intervalo que va de $\mu_{\bar X}-1.9\sigma_{\bar X}$ a $\mu_{\bar X}-0.4\sigma_{\bar X}$ Suponga que las medias muestrales se pueden medir con cual grado de precisión.


**Solución**
El intervalo de la media muestral $\bar X$ va $\mu_{\bar X}-1.9\sigma_{\bar X} = 40.5$ a $\mu_{\bar X}-0.4\sigma_{\bar X}=48$, entonces debemos calcular la probabilidad $P(40.5 \leq \bar X \leq 48)$ dado que $\mu_{\bar X}=50$ y  $\sigma_{\bar X}=5$. 

\begin{equation} 
\begin{split}
P(40.5 \leq \bar X \leq 48) & = P(\bar X \leq 48) - P(\bar X \geq 40.5) \\
& = 0.3445783 - 0.3445783 = 0.3158617\nonumber 
\end{split} 
\end{equation}

Calculo en R
```{r}
x <- pnorm(40.5, 50, 5)
y <- pnorm(48, 50, 5)
z <- y -x
x
y
z
```


2. UNa maquina de refrescos se ajusta para que la cantidad de bebidas que sirva promedie $240$ mililitros con una desviación estándar de 15 mililitros. La máquina se verifica periódicamente tomando una muestra de 40 bebidas y se calcula el contenido promedio. Si la media de las 40 bebidas es un valor dentro del intervalo $\mu_{\bar X} \frac{+}{-}2\sigma_{\bar X}$, se piensa que la máquina opera satisfactoriamente; de otra forma, se ajusta. Suponga que se revisa la maquina y se encuentra que la media de 40 bebidas es $\bar X = 271$ mililitros y se concluye que la máquina no necesita ajuste. ¿Esta es una decisión razonable?


**Solución**

No es razonable la decisión.



